feat(lambda): Validate SNS signature in lambda
aws/aws-js-sns-message-validator pull request #11
Opened 2017-04-26 10:31 UTC by emaincourt

Related to #2 and #10 

- Remove nil fields in the event to prevent wrong string to sign build. `Subject` field is always added to the SNS message and set to `null` on lambda handling, leading to the unability to create the string to sign. 

- Looks at both SigningCertURL and SigningCertUrl for the certificate url (related to #10 )

2017-06-13 09:51 UTC, aymericbeaumet requested changes

2017-06-13 09:51 UTC, aymericbeaumet commented on index.js
> +    const certificateUrl = message.SigningCertURL || message.SigningCertUrl;
Using `var` instead should allow the CI to pass on Node 0.10

2017-06-13 12:07 UTC, aymericbeaumet commented
@jeskew Any chance this could be considered for a merge?

Thanks!

2017-06-24 18:00 UTC, jeskew commented
Thanks for submitting, @emaincourt! Since Lambda message signatures are generated based on the canonical form of the SNS message, I think a better long-term fix is to simply convert all incoming messages to the HTTP(S) style message understood by this package.

I've opened a separate PR #13 that removes all Lambda-specific handling and instead changes the casing of `SigningCertUrl` and `UnsubscribeUrl` and removes `null` subjects.

2017-06-30 22:50 UTC, jeskew commented
Closing in favor of #13

2017-06-30 22:50 UTC, closed without merging